Feature/IL-300/scrollup
Sunagatov/Iced-Latte-Frontend pull request #120
Opened 2024-02-18 00:24 UTC by iakivpekarskyi

- added button to scroll up to the top of the screen
 - removed scale on buttons
 - minor fixes with margins

2024-02-18 17:04 UTC, DmitriyUshkvarok requested changes
the button after adding an item to cart should contain the text that the item is in cart and be locked
<img width="529" alt="addcart" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/d03657cd-4182-400e-9afe-77dcb3dcc444">

2024-02-19 17:43 UTC, iakivpekarskyi commented on src/components/Favourites/FavouritesFull/FavouritesFull.tsx
> +          <Button className="my-6 h-14 text-lg font-medium sm:w-[211px]">
fixed

2024-02-19 22:26 UTC, iakivpekarskyi commented on src/components/UI/Buttons/ScrollUpBtn/ScrollUpBtn.tsx
> +    </>
fixed

2024-02-19 22:46 UTC, iakivpekarskyi commented
> the button after adding an item to cart should contain the text that the item is in cart and be locked <img alt="addcart" width="529" src="https://private-user-images.githubusercontent.com/82167806/305732880-d03657cd-4182-400e-9afe-77dcb3dcc444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjIwODMsIm5iZiI6MTcwODM2MTc4MywicGF0aCI6Ii84MjE2NzgwNi8zMDU3MzI4ODAtZDAzNjU3Y2QtNDE4Mi00MDBlLTlhZmUtNzdkY2IzZGNjNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE2NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTcyZWQ5MjEwYjNiMmFlOTVkMjYyODU0NDEwYjM5YTRiNTgyMjI3NWE5MmI0ZTYxNzMxNTM4Mjg0MTIwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UugJf9-i5giXMhmw2oNk3B-HJvUWU1WFHrmBxtAgxZ0">

when item is added this button splits into two parts indicating that item was added

2024-02-20 11:25 UTC, DmitriyUshkvarok approved these changes

2024-02-23 19:34 UTC, merged