Feature/il 235/resetpass
Sunagatov/Iced-Latte-Frontend pull request #126
Opened 2024-02-26 00:31 UTC by iakivpekarskyi

- added changing password as a guest
- added changing password as a registered user
- added password confirm validation

2024-02-26 15:36 UTC, DmitriyUshkvarok commented on src/components/Auth/Modal/AuthModalLogin/AuthModal.tsx
> +    onCloseModal?.()
when you open the authorization modal window, reload the page and click on the forgot password link, the page changes and the modal window remains open.
<img width="622" alt="когда во время авторизации обновляю страницу и перехожу после на форгот ссылка меняется а модалка открыта" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/ceb823de-14ea-4b11-9b51-c98626154fd6">

2024-02-26 15:42 UTC, DmitriyUshkvarok commented on src/services/authService.ts
move user endpoints to user services
<img width="642" alt="authserv" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/168f23fa-3636-4c2d-a6fd-051f211dc557">

2024-02-26 15:44 UTC, DmitriyUshkvarok commented on src/validation/passwordSchema.ts
on the client side make a hint in validation in what format to enter the password as it is done in registration confirmation
<img width="540" alt="подсказку сделай в каом формате должен ввести пароль пользователь" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/6414bdd8-e1e8-4e74-950a-aa866bcfb438">

2024-02-26 15:50 UTC, DmitriyUshkvarok requested changes
1)add loaders for the forgot and reset pages
2)no validation for forgot password's email inpute
3)when reloading the page the Email is on the way component is reset!
4)when the page is refreshed, Password has been changed again.
5)when the user is authorized, when the page is refreshed, the form that refers to the unauthorized user Reset your password flickers.
<img width="283" alt="добавь лоадеры для страниц" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/ab0c6e12-7f53-4bba-8be3-60233b2dfddc">
<img width="1184" alt="отправляется запрос если поле пустое нет валидации на клиенте не одцентрован лоадер в кнопке кнопка меняет размер при загрузке" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/bed5b781-69a5-4ac5-b195-881d222ddf16">
<img width="752" alt="при обновлении страницы снова перебрасывает на форму" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/2bdf9a7c-2e35-4390-8511-e7d3348e65f0">
<img width="753" alt="при перезагрузке мигает форма когда авторизован" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/5739b1e3-960c-422f-83f0-cf4be98c22d8">
<img width="594" alt="при перезагрузке страницы сбрасывается стейт" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/82167806/d7893c6e-eca8-46d3-99a2-c24ff5221329">

2024-02-27 15:51 UTC, iakivpekarskyi commented on src/services/authService.ts
fixed

2024-02-27 15:58 UTC, iakivpekarskyi commented on src/validation/passwordSchema.ts
fixed

2024-02-29 21:47 UTC, iakivpekarskyi commented on src/components/Auth/Modal/AuthModalLogin/AuthModal.tsx
> +    onCloseModal?.()
fixed

2024-03-03 18:04 UTC, DmitriyUshkvarok commented on src/services/userService.ts
> +    '/auth/password/forgot',
move authorization-related endpoints to authorization services

2024-03-03 18:08 UTC, DmitriyUshkvarok commented on src/components/Auth/Modal/AuthModalLogin/AuthModal.tsx
> +  const handleForgotPasswordClick = () => {
I think the function handleForgotPasswordClick is unnecessary.
the resetOpenModal() function can be called in the onClick event of the Link component.

2024-03-03 18:12 UTC, DmitriyUshkvarok commented on src/components/Auth/ResetPassword/AuthResetPassForm.tsx
> +  const [resetSuccessful, setResetSuccessful] = useState(false)
I think this state should also be in the session repository.

2024-03-03 18:14 UTC, DmitriyUshkvarok commented on src/components/Auth/ResetPassword/ForgotPassForm.tsx
> +  const setStoredEmailSent = useLocalSessionStore((state) => state.setStoredEmailSent)
to reduce the code, perhaps we need to destructurize the states and functions from the storage?

2024-03-03 18:15 UTC, DmitriyUshkvarok commented on src/components/Auth/ResetPassword/ForgotPassForm.tsx
> +      localStorage.setItem('emailForReset', email)
I think email should be saved to a shared local session for more structured code

2024-03-03 18:17 UTC, DmitriyUshkvarok commented on src/components/Auth/ResetPassword/ForgotPassForm.tsx
> +            <Button type="submit" className="px-6">
button resizes on server load
fix this behavior

2024-03-03 18:20 UTC, DmitriyUshkvarok commented on src/components/Auth/ResetPassword/GuestResetPassForm.tsx
> +    const storedEmail = localStorage.getItem('emailForReset') ?? ''
when the e-mail is saved in the session store, call the state from the store.

2024-03-03 18:22 UTC, DmitriyUshkvarok commented on src/components/Auth/ResetPassword/GuestResetPassForm.tsx
> +            <Button type="submit" className="my-6 px-6">
button changes size when uploaded to the server

2024-03-03 18:24 UTC, DmitriyUshkvarok requested changes
if the password is successfully changed, the emailChanged state remains true. done

2024-03-11 20:42 UTC, Sunagatov approved these changes
Approved

2024-03-11 20:43 UTC, merged