fix: wrapped plus&minus with btn tag
Sunagatov/Iced-Latte-Frontend pull request #171
Opened 2024-04-23 21:26 UTC by iakivpekarskyi

1. added button tags to the counter

2024-04-24 06:56 UTC, Lightness322 approved these changes
Approved

2024-04-24 07:28 UTC, freecree submitted a review, later dismissed

2024-04-24 18:06 UTC, anksuunamun requested changes

2024-04-24 18:06 UTC, anksuunamun commented on src/components/UI/Counter/Counter.tsx
> +          className={
Событие нажатия должно быть у кнопки, а не у картинки, т.к. кнопка - интерактивный элемент, а картинка - это её украшение. То же касается и поведения, когда кол-во товара === 1. А cursor-pointer у кнопки итак при наведении есть по умолчанию и он не нужен вовсе.

2024-04-24 18:06 UTC, anksuunamun commented on src/components/UI/Counter/Counter.tsx
> +          onClick={onPlus}
Здесь т.ж.с., что и выше.

2024-04-24 21:47 UTC, iakivpekarskyi commented on src/components/UI/Counter/Counter.tsx
> +          className={
This component was made by another developer. There was some tricky logic in that - why he decided to stylize images to look and act like buttons but i don't know the reasoning for that. 

If i remove cursor-pointer styling - it is not shown for the all elements on the page for some reason. 

PS: just noticed lag while pressing minus and plus. 

Looks like we've found a rabbit hole...

2024-04-25 07:02 UTC, anksuunamun commented on src/components/UI/Counter/Counter.tsx
> +          className={
Лаг при нажатии "+" или "-" есть сейчас и в проде и он не относится к задаче. 
Я локально убрала 

>  cursor-pointer styling

и у меня такого эффекта, как ты описал нету.

![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/1f02de58-10dd-4fd5-9f56-176665d89106)

2024-04-26 16:10 UTC, iakivpekarskyi commented on src/components/UI/Counter/Counter.tsx
> +          className={
fixed.

2024-04-26 16:10 UTC, iakivpekarskyi commented on src/components/UI/Counter/Counter.tsx
> +          onClick={onPlus}
fixed.

2024-04-26 20:51 UTC, anksuunamun commented on src/components/UI/Counter/Counter.tsx
> +      <button id="min-btn" onClick={onMinus}>
pointer events потерял

2024-04-27 20:31 UTC, freecree approved these changes

2024-04-28 14:45 UTC, anksuunamun approved these changes

2024-04-28 15:42 UTC, Lightness322 approved these changes
Approved

2024-04-28 18:06 UTC, merged