[IL-332]: Implement filtering products by brand
Sunagatov/Iced-Latte-Frontend pull request #182
Opened 2024-04-28 20:01 UTC by freecree

1. Task's name:
Implement filtering products by brand

2. Developer's full name:
Bohdan Sidorov

3. Changes:

- add sidebar component with filters
- implement adaptive sidebar in ProductList
- add brand options to ProductList
- add request in useProducts with brand options

2024-04-29 07:23 UTC, Lightness322 reviewed
Reviewed

2024-04-29 07:23 UTC, Lightness322 commented on src/components/FilterSidebar/MobileFilterSidebar.tsx
> +  const sidebarRef = useRef<HTMLElement>(null)
You can replace "IMobileFilterSidebar" with "Readonly\<IMobileFilterSidebar\>" and remove "readonly" from interface. If you agree, you can change it here and in other places from this pull request

2024-04-29 19:46 UTC, anksuunamun requested changes

2024-04-29 19:46 UTC, anksuunamun commented on src/components/Product/ProductList/ProductList.tsx
> +    .filter(brandOption => brandOption.isChecked).map(brandOption => brandOption.value)
выбранные фильтры будут храниться в локальном состоянии и можно хранить их просто в виде массива строк, где значения - их values, т.к. они уникальны на беке и фронте.

2024-04-29 19:46 UTC, anksuunamun commented on src/components/Product/ProductList/ProductList.tsx
> +  const filtersContent = <Filters brandOptions={brandOptions} onBrandCheckboxChange={handleBrandCheckboxChange} />
тут излишне выносить в константу компонент

2024-04-29 19:46 UTC, anksuunamun commented on src/components/UI/Buttons/CircleCloseButton/CircleCloseButton.tsx
> +      onClick={onClick} onKeyDown={onClick}
тут точно нужен `onKeyDown`?

2024-04-29 19:46 UTC, anksuunamun commented on src/components/Product/ProductList/ProductList.tsx
> +            className='ml-auto'
Нужно вернуть класс как был, т.к. такое положение сайдбара - это требование лида.

2024-05-01 09:59 UTC, freecree commented on src/components/Product/ProductList/ProductList.tsx
> +import FilterSidebar from '@/components/FilterSidebar/FilterSidebar'
Fixed

2024-05-01 09:59 UTC, freecree commented on src/components/Product/ProductList/ProductList.tsx
> +  const [brandOptions, updateBrandCheckboxes] = useImmer<ICheckboxFilterOption[]>([
Fixed

2024-05-01 10:00 UTC, freecree commented on src/components/Product/ProductList/ProductList.tsx
> +    .filter(brandOption => brandOption.isChecked).map(brandOption => brandOption.value)
Fixed

2024-05-01 10:00 UTC, freecree commented on src/components/Product/ProductList/ProductList.tsx
> +  const filtersContent = <Filters brandOptions={brandOptions} onBrandCheckboxChange={handleBrandCheckboxChange} />
Fixed

2024-05-01 10:00 UTC, freecree commented on src/components/UI/Buttons/CircleCloseButton/CircleCloseButton.tsx
> +      onClick={onClick} onKeyDown={onClick}
Fixed

2024-05-02 15:45 UTC, anksuunamun requested changes

2024-05-02 15:45 UTC, anksuunamun commented on src/components/Product/ProductList/ProductList.tsx
> +  const selectedBrandOptions = useProductFiltersStore(state => state.selectedBrandOptions)
Удали закомментированную строку, ты ведь перенес логику в другое место.

Лучше получить из зустанда метод так:
`const { selectedBrandOptions} = useProductFiltersStore();`

2024-05-02 15:45 UTC, anksuunamun commented on src/store/productFiltersStore.ts
> +      {
Ты забыл оставить нетронутым остальной стейт, который не меняешь:
`({
...state,
selectedBrandOptions: state.selectedBrandOptions.filter(option => option !== value),
})`

2024-05-02 15:45 UTC, anksuunamun commented on src/store/productFiltersStore.ts
> +        selectedBrandOptions: [...state.selectedBrandOptions, value]
т.ж.с., что и в `removeBrandOption`, остальной стейт не меняем

2024-05-02 15:45 UTC, anksuunamun commented on src/components/Product/FilterSidebar/Filters.tsx
> +  const selectedBrandOptions = useProductFiltersStore(state => state.selectedBrandOptions)
лучше тут всё нужное из стейта получить сразу:
`const {
selectedBrandOptions,
.......etc
} = useProductFiltersStore()`

2024-05-02 15:45 UTC, anksuunamun commented on src/components/Product/FilterSidebar/Filters.tsx
> +import Checkbox from '../../UI/Checkbox/Checkbox'
Не должно быть таких импортов. Посмотри в других файлах проекта, они начинаются с `@` и т.д.

2024-05-02 15:45 UTC, anksuunamun commented on src/components/UI/Buttons/CircleCloseButton/CircleCloseButton.tsx
> +export default function CircleCloseBtn({ onClick, ...restProps }: Readonly<ICircleCloseBtn>) {
Ты по сути все пропсы, переданные в `CircleCloseBtn` и передаешь в `button`.
Так что можно сделать уже сразу вот так:
`export default function CircleCloseBtn(props: Readonly<ICircleCloseBtn>) { ........`

`    <button
      className={
        'flex h-14 w-14 cursor-pointer items-center justify-center rounded-full bg-secondary focus:bg-inverted active:bg-fullpage-tint transition-all duration-500 ease-in-out transform hover:scale-105'
      }
      {...props}
    >`

2024-05-02 15:45 UTC, anksuunamun commented on src/types/ICheckboxFilterOption.ts
> +export interface ICheckboxFilterOption {
Наверное, понятнее будет, к чему этот фильтрующий чекбокс относится, если назвать интерфейс так: `IProductFilterOptionCheckbox`.

2024-05-02 19:02 UTC, freecree commented on src/components/Product/ProductList/ProductList.tsx
> +  const selectedBrandOptions = useProductFiltersStore(state => state.selectedBrandOptions)
Fixed

2024-05-02 19:02 UTC, freecree commented on src/store/productFiltersStore.ts
> +      {
Fixed

2024-05-02 19:02 UTC, freecree commented on src/store/productFiltersStore.ts
> +        selectedBrandOptions: [...state.selectedBrandOptions, value]
Fixed

2024-05-02 19:02 UTC, freecree commented on src/components/Product/FilterSidebar/Filters.tsx
> +  const selectedBrandOptions = useProductFiltersStore(state => state.selectedBrandOptions)
Fixed

2024-05-02 19:02 UTC, freecree commented on src/components/Product/FilterSidebar/Filters.tsx
> +import Checkbox from '../../UI/Checkbox/Checkbox'
Fixed

2024-05-02 19:03 UTC, freecree commented on src/components/UI/Buttons/CircleCloseButton/CircleCloseButton.tsx
> +export default function CircleCloseBtn({ onClick, ...restProps }: Readonly<ICircleCloseBtn>) {
Fixed

2024-05-02 19:03 UTC, freecree commented on src/types/ICheckboxFilterOption.ts
> +export interface ICheckboxFilterOption {
Fixed

2024-05-03 09:36 UTC, anksuunamun requested changes
Все, что просила поправил - класс.
Но тут какие-то проблемы с версткой:  (надо поправить)
![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/24ee9b7f-2300-4e6a-9330-2a9aa6a2fe11)

Еще, у меня почему-то скролл отображается, так должно быть? Может там как-то карточки продуктов должны меньше становиться или что-то такое. Уточни у дизайнеров про адаптивность макета сайта:
![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/ace8c0aa-8761-4317-897d-798b1ee3e06e)

2024-05-04 14:20 UTC, anksuunamun submitted a review, later dismissed

2024-05-04 14:31 UTC, anksuunamun approved these changes

2024-05-04 14:35 UTC, merged