[ISSUE-179]: (MAIN PAGE-PRODUCT'S CATALOG) Product Card (Average Rating + Reviews Count)
Sunagatov/Iced-Latte-Frontend pull request #185
Opened 2024-05-01 09:30 UTC by Lightness322

1. Task's name:
(MAIN PAGE-PRODUCT'S CATALOG) Product Card (Average Rating + Reviews Count)

2. Developer's full name:
Mikhail Dyubkov

3. Changes:
- add ProductRating component
- add rating + reviews count to product on main page (instead of hardcoded values)
- style changes

2024-05-02 09:21 UTC, freecree submitted a review, later dismissed

2024-05-02 15:15 UTC, anksuunamun requested changes

2024-05-02 15:15 UTC, anksuunamun commented on src/components/UI/ProductRating/ProductRating.tsx
> +  const formattedRating = new Intl.NumberFormat('ru', {
Уточнить у Зуфара, правильно ли при текущей реализации отображаются цифры рейтинга.

2024-05-02 15:15 UTC, anksuunamun commented on src/components/UI/ProductRating/ProductRating.tsx
> +export default function ProductRating({
Мне кажется, что папка `src/components/UI` не совсем подходит для компонента рейтинга, т.к. это какой-то повсеместно используемый в проекте контрол/кнопка/..., а что-то относящееся только к продукту и лучше перенести в `src/components/Product`.

Также можно в компонент `ProductRating` перенести и информацию о количестве отзывов. (Если хочется, можно как-то отразить это в названии, но можно и так оставить, т.к. в принципе текущее название тоже неплохо отражает назначение компонента.

2024-05-02 17:16 UTC, Lightness322 commented on src/types/ProductCard.ts
> +export interface CardProps {
fixed

2024-05-02 17:16 UTC, Lightness322 commented on src/types/ProductRating.ts
> +export interface ProductRatingProps {
fixed

2024-05-02 17:16 UTC, Lightness322 commented on src/components/UI/ProductRating/ProductRating.tsx
> +export default function ProductRating({
fixed

2024-05-03 06:33 UTC, freecree submitted a review, later dismissed

2024-05-03 09:26 UTC, anksuunamun commented on src/components/Product/ProductCard/ProductCard.tsx
> +                <ProductRating
Звёздочка и текст, если нету рейтинга, тоже ведь к компоненту рейтинга логично отнести.

2024-05-03 09:28 UTC, anksuunamun submitted a review, later dismissed

2024-05-03 10:29 UTC, anksuunamun approved these changes

2024-05-03 10:31 UTC, Lightness322 commented on src/components/Product/ProductCard/ProductCard.tsx
> +                <ProductRating
fixed

2024-05-03 10:55 UTC, Sunagatov approved these changes

2024-05-03 10:56 UTC, merged