Feature/is 210/header styles favourites counter
Sunagatov/Iced-Latte-Frontend pull request #220
Opened 2024-05-11 17:41 UTC by iakivpekarskyi

1. Added new styles to the "cart" and "favourites"
2. Added shadow to header.
3. Added counter to "favourites"
4. Replaced "favourites" and "cart" icons.
5. Added margin to layout so that content doesn't stick to the screen borders

2024-05-12 10:24 UTC, Lightness322 submitted a review, later dismissed
Approved

2024-05-14 11:14 UTC, anksuunamun requested changes
После изменений в ПР футер на странице корзины расположен неверно:
![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/796a2c57-c400-4603-b0d1-b3b6fdbb57f8)

2024-05-14 11:14 UTC, anksuunamun commented on src/components/Header/Header.tsx
> +          <span className="hidden items-center text-L sm:flex">Iced Latte</span>
На макете - IL.

2024-05-14 14:20 UTC, iakivpekarskyi commented on public/heart_black.svg
> -<svg width="20" height="19" viewBox="0 0 20 19" fill="none" xmlns="http://www.w3.org/2000/svg">
designers said it will be always grey.

2024-05-14 15:06 UTC, iakivpekarskyi commented on README.md
>  - [@anksuunamun-govorov](https://github.com/anksuunamun)
Wasn't me but fixed it.

2024-05-14 15:07 UTC, iakivpekarskyi commented on src/components/Header/Header.tsx
> +          <span className="hidden items-center text-L sm:flex">Iced Latte</span>
the dot is excessive.

2024-05-14 15:07 UTC, iakivpekarskyi commented
> После изменений в ПР футер на странице корзины расположен неверно: ![image](https://private-user-images.githubusercontent.com/51954048/330401719-796a2c57-c400-4603-b0d1-b3b6fdbb57f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTQ0NzgsIm5iZiI6MTcxNTY5NDE3OCwicGF0aCI6Ii81MTk1NDA0OC8zMzA0MDE3MTktNzk2YTJjNTctYzQwMC00NjAzLWIwZDEtYjNiNmZkYmI1N2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZTdjOGI2ZTRlMGQzMTdmNDQ5ODVlZjVjNTQ5NzBmNzI5ZmFhYWE0ZGJkYWViOWZhMjZlNDExMDdmYjgzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_bLLmap7mC_21i8L8jVnrw3_d0aZHR7LTShjQJQmGk)

fixed.

2024-05-14 18:09 UTC, anksuunamun commented on README.md
>  - [@anksuunamun-govorov](https://github.com/anksuunamun)
Thanks!)))

2024-05-14 18:12 UTC, anksuunamun approved these changes

2024-05-14 18:13 UTC, merged