Separate scroll
Sunagatov/Iced-Latte-Frontend pull request #251
Opened 2024-06-15 23:26 UTC by iakivpekarskyi

https://github.com/Sunagatov/Iced-Latte-Frontend/issues/243

When you scroll the main page down, filters sections are  pinned to the top of the screen and are always visible.

2024-06-16 07:44 UTC, Lightness322 submitted a review, later dismissed
Approved

2024-06-16 11:05 UTC, anksuunamun submitted a review, later dismissed

2024-06-21 22:00 UTC, anksuunamun requested changes
Задача выполнена, но под блоком с дропдауном и бейджами неправильный большой отступ:
в текущей ветке:
![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/829a9755-9d2c-4738-beb9-f39446d679c5)

на проде:
![image](https://github.com/Sunagatov/Iced-Latte-Frontend/assets/51954048/0a5bb77b-a360-462e-b441-380b7b17f596)

2024-06-22 00:33 UTC, iakivpekarskyi commented
fixed.

2024-06-22 07:55 UTC, anksuunamun approved these changes

2024-06-22 08:36 UTC, anksuunamun approved these changes

2024-06-22 09:06 UTC, merged