create component ButtonHeart
Sunagatov/Iced-Latte-Frontend pull request #41
Opened 2023-12-10 17:40 UTC by DmitriyUshkvarok

2023-12-10 21:05 UTC, Wdyffs requested changes

2023-12-10 21:05 UTC, Wdyffs commented on src/components/Heart/ButtonHeart.tsx
> +    <div
Use button here and set onClick on it

2023-12-10 21:05 UTC, Wdyffs commented on src/components/Heart/ButtonHeart.tsx
> +      <button onClick={onClick} type="button">
Remove this button tag

2023-12-14 11:25 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +
fix

2023-12-14 11:26 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +const ButtonHeart: React.FC<ButtonHeartProps> = ({
fix

2023-12-14 11:29 UTC, DmitriyUshkvarok commented on src/components/Heart/index.ts
fix

2023-12-14 11:30 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +  const imageUrl = active ? '/heart_full.svg' : '/heart_empty.svg'
fix

2023-12-14 11:34 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +      className={`duration-400 flex h-[54px] w-[54px] cursor-pointer items-center justify-center rounded-full bg-secondary transition ease-in-out hover:bg-[#D9D9D9] ${className}`}
fix

2023-12-14 11:36 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +          height={27}
fix

2023-12-14 11:38 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +      <button onClick={onClick} type="button">
fix

2023-12-16 18:56 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +    <div
fix

2023-12-16 19:02 UTC, Wdyffs requested changes

2023-12-16 19:02 UTC, Wdyffs commented on src/components/Heart/ButtonHeart.tsx
> +      className={`duration-400 hover:bg-hover-heart flex h-[54px] w-[54px] cursor-pointer items-center justify-center rounded-full bg-secondary transition ease-in-out ${className}`}
use className={twMerge('blablasba', className)}

2023-12-16 19:12 UTC, DmitriyUshkvarok commented on src/components/Heart/ButtonHeart.tsx
> +      className={`duration-400 hover:bg-hover-heart flex h-[54px] w-[54px] cursor-pointer items-center justify-center rounded-full bg-secondary transition ease-in-out ${className}`}
fix

2023-12-16 19:27 UTC, Wdyffs submitted a review, later dismissed

2023-12-16 20:00 UTC, Wdyffs approved these changes

2023-12-16 20:01 UTC, merged