fix error build app
Sunagatov/Iced-Latte-Frontend pull request #92
Opened 2024-01-22 12:40 UTC by DmitriyUshkvarok

2024-01-22 20:46 UTC, annstriganova requested changes
I'm getting error when I try to confirm registration:
<img width="468" alt="Screenshot 2024-01-22 at 21 41 57" src="https://github.com/Sunagatov/Iced-Latte-Frontend/assets/20650874/07b4e8c4-a86f-4cdc-a42b-41dd64b6a3f5">

The validation regex is incorrect as I pointed out there https://github.com/Sunagatov/Iced-Latte-Frontend/pull/82#discussion_r1458057271

Also, I see no need in `confirmPassword` label.

2024-01-22 21:02 UTC, annstriganova commented
Discussed in 1-1, misunderstood the user flow: I thought that the field is supposed to be filled with password, rather than with the code from the email. I suggest renaming **Confirm Password** button to **Confirm Registration** and suggest adding a tip, e.g. _Enter code that was sent to your email_. That's a work for another PR.

Approved.

2024-01-22 21:03 UTC, annstriganova approved these changes

2024-01-25 01:03 UTC, Sunagatov approved these changes
Approved

2024-01-25 01:03 UTC, merged